[versions]
androidGradlePlugin = "7.3.1"
androidxActivity = "1.6.0"
androidxLifecycle = "2.5.1"
androidxTest = "1.4.0"
compose = "1.2.1"
composeCompiler = "1.3.2"
composeNavigation = "2.5.2"
dagger = "2.44"
junit = "5.9.1"
kotlin = "1.7.20"
kotlinCoroutines = "1.6.4"
kotlinSerialization = "1.4.1"
mockk = "1.13.2"
robolectric = "4.9"
truth = "1.1.3"

[libraries]

# AndroidX
androidX-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidX-lifecycle-composeViewModelUtilities = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidX-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }

# Compose
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

# Dagger
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-navigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }

# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Test
test-androidx-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
test-junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
test-junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
test-truth = { module = "com.google.truth:truth", version.ref = "truth" }


# Plugins
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
hilt-agp = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }