[versions]
androidGradlePlugin = "7.4.0"
androidxActivity = "1.6.1"
androidxLifecycle = "2.5.1"
androidxTest = "1.5.2"
composeBom = "2023.01.00"
composeCompiler = "1.4.0"
composeNavigation = "2.5.3"
dagger = "2.44.2"
dependencyAnalysis = "1.18.0"
junit = "5.9.2"
kotlin = "1.8.0"
kotlinCoroutines = "1.6.4"
kotlinSerialization = "1.4.1"
ktor = "2.2.2"
mockk = "1.13.3"
robolectric = "4.9.2"
truth = "1.1.3"


[libraries]

# AndroidX
androidX-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidX-lifecycle-composeViewModelUtilities = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidX-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material = { group = "androidx.compose.material", name = "material3" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }

# Dagger
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-navigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }

# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Ktor
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging-jvm", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Test
test-androidx-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
test-junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
test-junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
test-ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
test-truth = { module = "com.google.truth:truth", version.ref = "truth" }

# Plugins
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
hilt-agp = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }


[bundles]
unitTest = ["test-junit-api", "test-junit-engine", "test-mockk", "test-truth"]
ktor-client = ["ktor-client-contentNegotiation", "ktor-client-json", "ktor-client-logging", "ktor-client-okhttp", "ktor-client-serialization"]


[plugins]
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
